<a href="https://colab.research.google.com/github/JennaSanks/ML_Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. What is NumPy?**

**Definition:**

NumPy (Numerical Python) is a Python library used for creating and working with arrays and performing fast mathematical operations on them.

Think of NumPy as a supercharged version of Python lists that's designed for numbers.

**You import it like this:**

In [ ]:
import numpy as np

**Here:**

numpy is the library name.

np is an alias (short nickname).

**2. Why was NumPy created?**

Before NumPy existed, Python only had lists.


In [ ]:
numbers = [1, 2, 3, 4, 5]


**Lists are great, but they have problems:**

1. Slower for large calculations

2. Can't do element-wise math easily

3. Use more memory

4. Not built for scientific computing

In [ ]:
numbers = [1, 2, 3]

print(numbers * 2)

[1, 2, 3, 1, 2, 3]


**You might expect:**

*[2, 4, 6]*

But Python interprets * 2 for a list as "repeat the list twice."

**Now with NumPy:**

In [ ]:
import numpy as np

numbers = np.array([1, 2, 3])

print(numbers * 2)

[2 4 6]



NumPy performs the multiplication on each element.

**Array Creation**

Everything in NumPy starts with an array.

**1. np.array()**

Syntax:

In [ ]:
np.array(object)

array(<class 'object'>, dtype=object)

The np.array(object) syntax is used to create a NumPy array from a Python list or other array-like object.

The object placeholder means you can pass in any sequence (like a list or tuple) of numbers, and NumPy will convert it into an ndarray (N-dimensional array).

Example:

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)

[10 20 30 40]


**2. arr.shape**

Returns the dimensions of an array.

In [ ]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.shape)

(2, 3)


**Meaning:**

2 rows

3 columns

**3. arr.ndim**

Returns number of dimensions.

In [ ]:
import numpy as np

arr = np.array([[1,2],[3,4]])

print(arr.ndim)

2


**4. arr.size**

Total number of elements.

In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

print(arr.size)

6


**5. arr.dtype**

Returns data type.

In [ ]:
import numpy as np

arr=np.array([1,2,3])

print(arr.dtype)

int64


When you see int64 for arr.dtype, it means that the elements in your NumPy array are integers, and each integer is stored using 64 bits of memory.

This allows for a very large range of integer values to be represented.

NumPy automatically chooses the most appropriate data type for your array elements unless specified otherwise.



In [ ]:
arr=np.array([1.5,2.3])

print(arr.dtype)

float64


**6. np.arange()**

Creates numbers in a range.

In [ ]:
import numpy as np

arr=np.arange(1,11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Step:

In [ ]:
arr=np.arange(0,20,2)

print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


**7. np.linspace()**

Creates equally spaced numbers.

In [ ]:
import numpy as np

arr=np.linspace(0,100,5)

print(arr)

[  0.  25.  50.  75. 100.]


working:

0 (start): This is the starting value of your sequence. So, your array begins with 0.

100 (stop): This is the ending value of your sequence. Unlike np.arange(), the stop value is included in the array. So, your array ends with 100.

5 (num): This is the number of samples (elements) you want to generate. np.linspace will calculate the appropriate spacing to fit exactly 5 numbers between 0 and 100, inclusive.

**8. np.zeros()**

Used for initializing matrices.

In [ ]:
import numpy as np

arr=np.zeros((2,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


**9. np.ones()**

In [ ]:
import numpy as np

arr=np.ones((3,2))

print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


**10. np.full()**

Fill with one value.

In [ ]:
import numpy as np

arr=np.full((2,2),9)

print(arr)

[[9 9]
 [9 9]]


**11. Indexing**

In [ ]:
import numpy as np

arr=np.array([10,20,30,40])

print(arr[0])
print(arr[2])
print(arr[-1]) #Negative indexing

10
30
40


**12. Slicing**

In [ ]:
import numpy as np

arr=np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


**13. 2D Indexing**

In [ ]:
import numpy as np

arr=np.array([
    [1,2,3],
    [4,5,6]
])

print(arr[1,2])

6


**14. reshape()**

Changes shape.

In [ ]:
import numpy as np

arr=np.arange(1,7)

print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


**15. flatten()**

Convert to 1D.

In [ ]:
import numpy as np

arr=np.array([[1,2],[3,4]])

print(arr.flatten())

[1 2 3 4]


**16. Mathematical Operations**

In [ ]:
import numpy as np

a=np.array([1,2,3])

# Addition
print(a+5)

# Multiplication
print(a*10)

# Square
print(a**2)

[6 7 8]
[10 20 30]
[1 4 9]


**17. Statistics**

In [ ]:
import numpy as np

a=np.array([10,20,30])

# Mean
print(np.mean(a))

# Sum
print(np.sum(a))

# Maximum
print(np.max(a))

# Minimum
print(np.min(a))

# Standard Deviation
print(np.std(a))

20.0
60
30
10
8.16496580927726


**18. Boolean Indexing**

In [ ]:
import numpy as np

a=np.array([2,5,8,1,10])

print(a>5)
print(a[a>5]) # Filtering

[False False  True False  True]
[ 8 10]


**19. np.where()**

In [ ]:
import numpy as np

a=np.array([2,7,9,4])

print(np.where(a>5))

(array([1, 2]),)


**Meaning:**

Elements greater than 5 are at indices 1 and 2.

You can also replace values conditionally:

In [ ]:
result = np.where(a > 5, 100, 0)

print(result)

[  0 100 100   0]


np.where(condition, value_if_true, value_if_false) works like a 'find and replace' based on a condition.

It goes through each item in the array a:

If an item is greater than 5 (the condition is True), it replaces that item with 100 (the value_if_true).

If an item is not greater than 5 (the condition is False), it replaces that item with 0 (the value_if_false).

**20. np.sort()**

In [ ]:
import numpy as np

a=np.array([5,1,9,3])

print(np.sort(a))

[1 3 5 9]


**21. np.unique()**

Removes duplicates.

In [ ]:
import numpy as np

a=np.array([1,2,2,3,3,3])

print(np.unique(a))

[1 2 3]


**22. Random Numbers**

Random integers

In [ ]:
import numpy as np

print(np.random.randint(1,10,5))

[8 3 8 3 2]


(Random output changes every run.)

Random decimal numbers

In [ ]:
print(np.random.rand(3))

[0.76182091 0.35320078 0.28303368]


**23. Matrix Multiplication (np.dot())**

In [ ]:
  import numpy as np

a=np.array([[1,2],
            [3,4]])

b=np.array([[5,6],
            [7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


**Extra**

**1. Broadcasting**

Definition:

Broadcasting is NumPy's ability to perform operations on arrays of different shapes without manually repeating values.

Instead of writing:

[1+5, 2+5, 3+5]

NumPy automatically broadcasts 5 across the array.

In [ ]:
# Example
import numpy as np

a = np.array([1, 2, 3])

print(a + 5)

[6 7 8]


In [ ]:
import numpy as np

a = np.array([[1],
              [2],
              [3]])

b = np.array([10, 20, 30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


**2. Axis**

This is one of the most confusing concepts.

Consider:

In [ ]:
import numpy as np

a = np.array([
    [1,2,3],
    [4,5,6]
])

# Rows ↓
# 1 2 3
# 4 5 6
# Columns →

# axis=0
# Works down the rows (column-wise).
print(np.sum(a, axis=0))

# axis=1
# Works across the columns (row-wise).

print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


**Memory Trick**


*   axis=0 → Move down each column.
*   axis=1 → Move across each row.


**3. Vectorization**

Never write loops if NumPy can do it.

In [ ]:
# Bad
result=[]

for i in range(5):
    result.append(i*2)

In [ ]:
# Good
import numpy as np

a=np.arange(5)

print(a*2)

[0 2 4 6 8]


**Vectorized code is:**

*   Faster
*   Shorter
*   Easier to read

**4. Copy vs View**

This causes many bugs.

In [ ]:
# View
import numpy as np

a=np.array([1,2,3])

b=a

b[0]=100

print(a)

[100   2   3]


Both variables refer to the same array.

In [ ]:
# Copy
import numpy as np

a=np.array([1,2,3])

b=a.copy()

b[0]=100

print(a)
print(b)

[1 2 3]
[100   2   3]


**5. Data Types (dtype)**

In [ ]:
a=np.array([1,2,3])

print(a.dtype)

int64


In [ ]:
# Change type
a=a.astype(float)

print(a)

[1. 2. 3.]


Common types:
*   int32

*   int64

*   float32

*   float64

*   bool

**6. Fancy Indexing**

Select multiple positions at once.

In [ ]:
import numpy as np

a=np.array([10,20,30,40,50])

print(a[[0,2,4]])

[10 30 50]


**7. Boolean Masking**

Very common in ML.

In [ ]:
import numpy as np

marks=np.array([25,80,91,40,70])

passed=marks>=50

print(marks[passed])

[80 91 70]


*88. Matrix Multiplication vs Multiplication**

In [ ]:
# Element-wise

a*b

In [ ]:
# Matrix multiplication

a@b

or

np.matmul(a,b)

or

np.dot(a,b)

# These are not the same.

**9. Reshape Rules**

In [ ]:
a=np.arange(12)

print(a.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Works because

*3×4=12*

This won't work:

*a.reshape(5,5)*


Error

Because

5×5=25

You only have 12 elements.

**10. -1 in reshape()**

NumPy can calculate one dimension automatically.

In [ ]:
a=np.arange(12)

print(a.reshape(3,-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**11. Memory Order (Basic Awareness)**

NumPy stores arrays efficiently in contiguous memory, which is one reason it's much faster than Python lists. You don't need to master memory layouts immediately, but knowing that contiguous arrays are generally faster is useful.

**12. Random Seed**


In [ ]:
# Without a seed:
import numpy as np

print(np.random.randint(1,10,5))

[3 7 8 5 4]


Every run gives different numbers.

In [ ]:
# With a seed:
import numpy as np

np.random.seed(42)

print(np.random.randint(1,10,5))

[7 4 8 5 7]


The same random numbers are generated every time, making experiments reproducible.

**13. Universal Functions (ufuncs)**

Functions like:

In [ ]:
np.sqrt()
np.sin()
np.exp()
np.log()

are called universal functions (ufuncs).

They operate element-wise.

Example

In [ ]:
a=np.array([1,4,9])

print(np.sqrt(a))

[1. 2. 3.]


**14. Arrays are Mutable**

In [ ]:
a=np.array([1,2,3])

a[0]=100

print(a)

[100   2   3]


Unlike strings, NumPy arrays can be modified after creation.

**15. The @ Operator**

Instead of writing:

In [ ]:
np.matmul(a,b)

you can write:

In [ ]:
a @ b


This is the modern and most readable syntax for matrix multiplication.