<a href="https://colab.research.google.com/github/JennaSanks/ML_Libraries/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch

**What is PyTorch?**

* PyTorch is an open-source deep learning framework developed by Meta (formerly Facebook).
* It is primarily used to build and train neural networks for tasks involving images, text, audio, video, and many other types of data.

* While Scikit-learn is mainly for classical machine learning, PyTorch is designed for deep learning.

**Why is PyTorch used?**

PyTorch helps you:

* Build neural networks
* Train deep learning models
* Use GPUs for faster training
* Perform automatic differentiation (compute gradients automatically)
* Build custom AI architectures
* Research and deploy AI applications

## torch.tensor()

**Why it's used**

Everything in PyTorch is stored as a tensor. Before a model can process data (images, text, numbers, labels), it must be converted into tensors.

In [ ]:
import torch

x = torch.tensor([10, 20, 30])
print(x)

tensor([10, 20, 30])


**Explanation**

* Creates a PyTorch tensor.
* Converts the Python list into a tensor.
* Everything in PyTorch (inputs, outputs, weights, labels) is stored as tensors.

## torch.zeros()

**Why it's used**

Used to initialize tensors with zeros. You'll often use it for creating placeholders, masks, or initializing values before updating them.

In [ ]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Explanation**

* Creates a tensor filled with 0.
* 2 = rows, 3 = columns.
* Commonly used to initialize tensors.

# torch.ones()

**Why it's used**

Creates a tensor filled with 1s. Used to initialize weights, masks, or tensors with a constant value, and for testing.

In [ ]:
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


**Explanation**

* Creates a tensor filled with 1.
* Often used for initialization and testing.

## torch.empty()

**Why it's used**

Creates an uninitialized tensor. Used when you'll immediately overwrite the values, making it faster than initializing with zeros or ones.

In [ ]:
x = torch.empty(2, 3)
print(x)

tensor([[2.7169e-19, 0.0000e+00, 2.3551e-16],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])


Explanation

* Creates an uninitialized tensor.
* Values are random because memory is allocated but not filled.
* Faster than zeros() when you'll overwrite the values immediately.

##torch.arange()

**Why it's used**

Creates a sequence of numbers with a fixed step size. Used for ranges, indexing, loops, and generating integer sequences.

In [ ]:
x = torch.arange(0, 10, 2)
print(x)

tensor([0, 2, 4, 6, 8])


Explanation

* Creates equally spaced values.
* Format: start, stop, step.

##torch.linspace()

**Why it's used**

Creates a fixed number of evenly spaced values between two endpoints. Used for sampling continuous values, plotting, and numerical computations.

In [ ]:
x = torch.linspace(0, 1, 5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


Explanation

* Creates a fixed number of evenly spaced values.
* Here it generates 5 numbers between 0 and 1.

##torch.rand()

**Why it's used**

Neural networks usually start with random weights. torch.rand() generates random values between 0 and 1, making it useful for initialization and creating sample data.

In [ ]:
x = torch.rand(2, 3)
print(x)

tensor([[0.1104, 0.3235, 0.5706],
        [0.9144, 0.9637, 0.3042]])


**Explanation**

Every time you run it, the values will be different.

##reshape()

In [ ]:
x = torch.arange(6)

y = x.reshape(2, 3)

print(y)

tensor([[0, 1, 2],
        [3, 4, 5]])


**Why it's used**

Models expect data in specific shapes. reshape() changes how data is arranged without changing the actual values.



Explanation

**Before:**

    tensor([0, 1, 2, 3, 4, 5])

**After:**

    tensor([[0, 1, 2],
            [3, 4, 5]])

The values stay the same; only their arrangement changes.

##nn.Linear()

In [ ]:
import torch.nn as nn
layer = nn.Linear(3, 2)
x = torch.rand(1, 3)
output = layer(x)
print(output)


tensor([[ 0.0630, -0.7186]], grad_fn=<AddmmBackward0>)


**Why it's used**

Creates a fully connected (dense) layer, one of the most common building blocks in neural networks. It learns the relationship between input features and outputs.

**Explanation**
* 3 → number of input features.
* 2 → number of output features.
* The layer automatically creates and learns weights and biases during training.

##torch.randn()

**Why it's used**

Generates random numbers from a normal (Gaussian) distribution with a mean of 0 and a standard deviation of 1.

It is mainly used to initialize weights of neural networks, because values centered around 0 help models train better.

In [1]:
import torch

x = torch.randn(2, 3)
print(x)

tensor([[ 1.6694,  0.7820, -0.0112],
        [ 1.3793,  0.4644,  1.3781]])


Output (changes every run)

**Explanation**
* Creates a tensor with 2 rows and 3 columns.
* Values can be positive or negative.
* Numbers are generated from a normal distribution.

##torch.randint()

**Why it's used**

Generates random integers within a given range.

Useful for:

* Creating random class labels.
* Random indices.
* Testing models.

In [27]:
import torch

x = torch.randint(0, 10, (2, 3))
print(x)

tensor([[0, 4, 0],
        [3, 8, 4]])


Output (changes every run)

**Explanation**

* 0 → minimum value (inclusive).
* 10 → maximum value (exclusive).
* (2, 3) → output shape.

The tensor contains random integers from 0 to 9.

##torch.manual_seed()

**Why it's used**

Normally, random functions produce different values every time you run your code.

*torch.manual_seed()* fixes the random number generator so you get the same random values every run.

This makes experiments reproducible.

In [26]:
import torch

torch.manual_seed(42)

x = torch.rand(2, 3)

print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


Output (will be the same every time)

**Explanation**
* 42 is called the seed.
* You can use any integer (1, 10, 100, 999, etc.).
* The same seed always produces the same sequence of random numbers.

# Tensor Properties

These properties help you understand a tensor's shape, size, type, and where it's stored. You'll use them almost every day when working with PyTorch.

##shape

**Why it's used**

Tells you the dimensions (rows, columns, etc.) of a tensor.

In [25]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

torch.Size([2, 3])


**Explanation**

    2 → rows
    3 → columns

shape is the quickest way to check a tensor's dimensions.

##size()

**Why it's used**

Returns the size (dimensions) of a tensor.

In [24]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.size())

torch.Size([2, 3])


**Explanation**

*size()* and *shape* return the same result.

Both are commonly used.

In [23]:
# Example:

print(x.shape)
print(x.size())

torch.Size([3])
torch.Size([3])


Both print

    torch.Size([2, 3])

##dtype

**Why it's used**

Tells you what type of data is stored in the tensor.

In [22]:
import torch

x = torch.tensor([1, 2, 3])

print(x.dtype)

torch.int64


**Explanation**

Here the tensor stores integers.

In [21]:
# Another example:

x = torch.tensor([1.5, 2.5])

print(x.dtype)

torch.float32


**Common data types:**

* torch.int64 → Integers
* torch.float32 → Decimal numbers (most commonly used in deep learning)
* torch.bool → True/False

##device

**Why it's used**

Tells you whether the tensor is stored on the CPU or GPU.

In [20]:
import torch

x = torch.tensor([1, 2, 3])

print(x.device)

cpu


Output (if using CPU)

**Explanation**

If you're using a GPU, the output may be:

    cuda:0

Knowing the device is important because the model and data must be on the same device.

##ndim

**Why it's used**

Returns the number of dimensions (axes) of a tensor.

In [19]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.ndim)

2


**Explanation**

Examples:

    torch.tensor(5)

Dimensions = 0

    torch.tensor([1, 2, 3])

Dimensions = 1

    torch.tensor([[1, 2],
                  [3, 4]])

Dimensions = 2

    torch.rand(3, 32, 32)

Dimensions = 3

The more axes a tensor has, the higher its dimensions.

##numel()

**Why it's used**

Returns the total number of elements in the tensor.

In [18]:
import torch


x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.numel())

6


**Explanation**

The tensor has:

* 2 rows
* 3 columns

So,

    2 × 3 = 6 elements

*numel()* simply counts all elements.

#Tensor Data Type Conversion

Sometimes you'll need to change the data type of a tensor. This is very common because many PyTorch functions (especially in deep learning) expect tensors of a specific type.

##float()

**Why it's used**

Converts a tensor to floating-point numbers (float32).

Most neural networks require input data to be float32.

In [17]:
import torch

x = torch.tensor([1, 2, 3])

print(x.dtype)

x = x.float()

print(x.dtype)

torch.int64
torch.float32


**Explanation**

Initially, x stores integers.
float() converts every value to a decimal number.
Values become 1.0, 2.0, 3.0 internally.

##int()

**Why it's used**

Converts a tensor to integers.

Useful when decimal values are not needed.

In [16]:
import torch

x = torch.tensor([1.7, 2.8, 3.9])

x = x.int()

print(x)

tensor([1, 2, 3], dtype=torch.int32)


**Explanation**

* Removes the decimal part.
* It **does not round** the number.
* 1.7 → 1
* 2.8 → 2

## long()

**Why it's used**

Converts a tensor to 64-bit integers (int64).

This is the required data type for labels used with many loss functions like CrossEntropyLoss.

In [15]:
import torch

x = torch.tensor([1.2, 2.9])

x = x.long()

print(x)
print(x.dtype)

tensor([1, 2])
torch.int64


**Explanation**

* Converts values to integers.
* Stores them as int64.

##bool()

**Why it's used**

Converts values into True or False.

Useful for creating masks and filtering data.

In [14]:
import torch

x = torch.tensor([1, 0, 3, 0])

x = x.bool()

print(x)

tensor([ True, False,  True, False])


**Explanation**
* 0 becomes False.
* Any non-zero value becomes True.

##type()

**Why it's used**

Converts a tensor to any specific data type.

Less commonly used than .float() or .long(), but useful when you want precise control.

In [13]:
import torch

x = torch.tensor([1, 2, 3])

x = x.type(torch.float32)

print(x.dtype)

torch.float32


**Explanation**
* Converts the tensor to the specified type.
* You can replace torch.float32 with other types like torch.int64, torch.bool, etc.

#Tensor Indexing & Slicing

Indexing and slicing let you access or modify specific values in a tensor. This is used constantly while preparing data for machine learning.

##Access a Single Element

**Why it's used**

To get a specific value from a tensor.

In [12]:
import torch

x = torch.tensor([10, 20, 30, 40])

print(x[2])

tensor(30)


**Explanation**
* Indexing starts from 0.
* x[2] means the 3rd element.

      Index : 0   1   2   3
      Value :10  20  30  40

##Negative Indexing

**Why it's used**

To access elements from the end.

In [11]:
import torch

x = torch.tensor([10, 20, 30, 40])

print(x[-1])

tensor(40)


**Explanation**

      -1 → Last element
      -2 → Second last
      -3 → Third last

##Slicing

**Why it's used**

To extract multiple elements.

In [10]:
import torch

x = torch.tensor([10, 20, 30, 40, 50])

print(x[1:4])

tensor([20, 30, 40])


**Explanation

        Start : 1 (included)

        Stop : 4 (excluded)

So it returns

        20 30 40

##Slice from Beginning

In [9]:
import torch

x = torch.tensor([10, 20, 30, 40, 50])

print(x[:3])

tensor([10, 20, 30])


**Explanation**

Starts from the beginning and stops before index 3.

##Slice till End

In [8]:
import torch

x = torch.tensor([10, 20, 30, 40, 50])

print(x[2:])

tensor([30, 40, 50])


**Explanation**

Starts at index 2 and goes until the end.

##Step Slicing

**Why it's used**

To skip elements.

In [7]:
import torch

x = torch.tensor([10, 20, 30, 40, 50, 60])

print(x[::2])

tensor([10, 30, 50])


**Explanation**

    Start → Beginning

    Stop → End

    Step → 2

It picks every second element.

##Indexing 2D Tensors

In [6]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x[1, 2])

tensor(6)


**Explanation**

      Row 1

      Column 2

      [[1,2,3],
      [4,5,6]]
            ↑

##Access a Complete Row

In [5]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x[0])

tensor([1, 2, 3])


**Explanation**

Returns the first row.

##Access a Complete Column

In [4]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x[:, 1])

tensor([2, 5])


**Explanation**

    :  → All rows

    1 → Second column

So it returns

    2

    5

##Modify an Element

**Why it's used**

To update values inside a tensor.

In [3]:
import torch

x = torch.tensor([10, 20, 30])

x[1] = 100

print(x)

tensor([ 10, 100,  30])


**Explanation**

The value at index 1 is replaced with 100.

##Modify an Entire Row

In [2]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

x[0] = torch.tensor([7, 8, 9])

print(x)

tensor([[7, 8, 9],
        [4, 5, 6]])


**Explanation**

The entire first row is replaced.

##Boolean Indexing

**Why it's used**

To select elements that satisfy a condition.

In [1]:
import torch

x = torch.tensor([10, 20, 30, 40, 50])

print(x[x > 25])

tensor([30, 40, 50])


**Explanation**

* x > 25 creates a mask:

      [False, False, True, True, True]

* Only elements where the mask is True are returned.

This is heavily used for filtering data.