<a href="https://colab.research.google.com/github/JennaSanks/ML_Libraries/blob/main/Scikitlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Preparation**

**1. train_test_split()**

Use

Splits the dataset into training and testing data.


Why?

To train the model on one part of the data and test it on unseen data.

In [ ]:
# Syntax
train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Example
from sklearn.model_selection import train_test_split
import pandas as pd

df = pd.DataFrame({
    "Hours": [1,2,3,4,5],
    "Marks": [20,40,60,80,100]
})

X = df[["Hours"]]
y = df["Marks"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train)
print(X_test)

   Hours
4      5
2      3
0      1
3      4
   Hours
1      2


**When to Use**

Before training almost every ML model.


**2. StandardScaler**
Use

Standardizes numerical features so they have a mean of 0 and a standard deviation of 1.


Why?

Some ML algorithms (like SVM, KNN, Logistic Regression, PCA) work much better when features are on a similar scale.

In [ ]:
# Syntax
StandardScaler()

In [ ]:
# Example
from sklearn.preprocessing import StandardScaler
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40]
})

scaler = StandardScaler()

scaled_data = scaler.fit_transform(df)

print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


**When to Use**

Before training models like:

      SVM
      KNN
      Logistic Regression
      Linear Regression (often helpful)
      PCA

In [ ]:
# Common Mistake

# Don't do:

scaler.fit_transform(X_test)

In [ ]:
# Instead:

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

This avoids leaking information from the test set into the training process.

**3. MinMaxScaler**

Use

Scales numerical values to a fixed range, usually 0 to 1.

Why?

When features have very different ranges (e.g., Age = 20–60, Salary = 30,000–100,000), large values can dominate smaller ones. MinMaxScaler brings them to the same scale.

**Formula:**

Scaled Value=
(Value−Minimum) / (Maximum−Minimum)

This makes:

    Minimum value → 0

    Maximum value → 1

In [ ]:
# Syntax
MinMaxScaler()

In [ ]:
# Example
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40]
})

scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(df)

print(scaled_data)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


**When to Use**
* Neural Networks
* KNN
* K-Means Clustering
* Algorithms that use distances or gradients
* When you want all features between 0 and 1



In [ ]:
# Don't do
scaler.fit_transform(X_test)

In [ ]:
# Do this instead:

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**4. RobustScaler**

Use

Scales numerical data while reducing the effect of outliers.


Why?

If your dataset contains extreme values (outliers), StandardScaler and MinMaxScaler can be heavily influenced by them. RobustScaler uses the median and Interquartile Range (IQR), making it much more resistant to outliers.

In [ ]:
# Syntax
RobustScaler()

In [ ]:
# Example
from sklearn.preprocessing import RobustScaler
import pandas as pd

df = pd.DataFrame({
    "Salary": [30000, 35000, 40000, 45000, 1000000]
})

scaler = RobustScaler()

scaled_data = scaler.fit_transform(df)

print(scaled_data)

[[-1. ]
 [-0.5]
 [ 0. ]
 [ 0.5]
 [96. ]]


Notice that the outlier (1000000) still has a large value, but it doesn't distort the scaling of the normal values as much as MinMaxScaler or StandardScaler would.

**When to Use**
* Data contains outliers
* Financial data
* Salary data
* House prices
* Medical datasets

**Don't use it just because it's available.**

If your data doesn't have significant outliers, StandardScaler is usually the better choice.

Also remember:

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**5. Normalizer**

Use

Scales each row (sample) so its length (magnitude) becomes 1.


Why?

Unlike StandardScaler and MinMaxScaler, which scale columns (features), Normalizer scales each row independently. It's useful when the direction of the data matters more than its magnitude.

In [ ]:
# Syntax
Normalizer()

In [ ]:
# Example
from sklearn.preprocessing import Normalizer
import pandas as pd

df = pd.DataFrame({
    "Math": [3, 1],
    "Science": [4, 2]
})

normalizer = Normalizer()

normalized_data = normalizer.fit_transform(df)

print(normalized_data)

[[0.6        0.8       ]
 [0.4472136  0.89442719]]


**When to Use**
* Text classification (TF-IDF vectors)
* Cosine similarity
* Document similarity
* Recommendation systems


**Common Mistake**

Many beginners confuse Normalizer with StandardScaler.

* StandardScaler → Scales columns (features).
* Normalizer → Scales rows (samples).

They solve different problems.

**6. LabelEncoder**

Use

Converts categorical (text) labels into numbers.

Why?

Machine Learning models can't work directly with text like "Cat" or "Dog". LabelEncoder converts them into integers.

In [ ]:
# Syntax
LabelEncoder()

In [ ]:
# Example
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.DataFrame({
    "Animal": ["Cat", "Dog", "Bird", "Dog", "Cat"]
})

encoder = LabelEncoder()

df["Animal"] = encoder.fit_transform(df["Animal"])

print(df)

   Animal
0       1
1       2
2       0
3       2
4       1


**When to Use**
* Encoding the target (y) column.
* Binary classification labels like:
  * Yes / No
  * Spam / Not Spam
  * Pass / Fail

**Don't use LabelEncoder on input features (X) when the categories have no natural order.**

**Bad example:**

    Red   → 0

    Blue  → 1

    Green → 2

**The model may think:**

    Green > Blue > Red

which is not true.

For such features, use OneHotEncoder instead.

**7. OneHotEncoder**

Use

Converts categorical features into multiple binary (0 or 1) columns.

Why?

Unlike LabelEncoder, OneHotEncoder doesn't create a false numerical order between categories.

In [ ]:
# Syntax
OneHotEncoder()

In [ ]:
# Example
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red"]
})

encoder = OneHotEncoder(sparse_output=False)

encoded_data = encoder.fit_transform(df)

print(encoded_data)

print(encoder.get_feature_names_out()) # Get Column Names

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
['Color_Blue' 'Color_Green' 'Color_Red']


**When to Use**
* Input features (X) with categories like:
  *  Color
  *  City
  *  Country
  *  Gender
  *  Department
  *  Product Type

**Don't use LabelEncoder for categorical input features like:**

    Red

    Blue

    Green

**because**

    Red → 2

    Blue → 0

    Green → 1

makes the model think there's an order, which doesn't exist.

**Use:**

    OneHotEncoder()

instead.

**8. OrdinalEncoder**

Use

Converts categorical features with a natural order into numbers.

Why?

Some categories have a meaningful ranking, so assigning numbers preserves that order.

Examples:

Small < Medium < Large
Low < Medium < High
Beginner < Intermediate < Advanced

In [ ]:
# Syntax
OrdinalEncoder()

In [ ]:
# Example
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

df = pd.DataFrame({
    "Size": ["Small", "Medium", "Large", "Small"]
})

encoder = OrdinalEncoder(
    categories=[["Small", "Medium", "Large"]]
)

df["Size"] = encoder.fit_transform(df[["Size"]])

print(df)

   Size
0   0.0
1   1.0
2   2.0
3   0.0


**When to Use**

Use when categories have a natural order, such as:

* Education Level
* T-Shirt Size
* Customer Rating
* Experience Level
* Satisfaction Level


**Don't use OrdinalEncoder for unordered categories.**

**Bad example:**

    Red

    Blue

    Green

**Encoding them as**

    Red   → 0

    Blue  → 1

    Green → 2

**incorrectly suggests:**

    Green > Blue > Red

which has no real meaning.

Use

      OneHotEncoder

instead.

**9. SimpleImputer**

Use

Fills missing values (NaN) in a dataset.

Why?

Most machine learning algorithms cannot work with missing values. SimpleImputer replaces them with a suitable value.

In [ ]:
# Syntax
SimpleImputer(strategy="mean")

In [ ]:
# Example 1: Mean Strategy
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, 25, np.nan, 35, 40]
})

imputer = SimpleImputer(strategy="mean")

df["Age"] = imputer.fit_transform(df[["Age"]])

print(df)

    Age
0  20.0
1  25.0
2  30.0
3  35.0
4  40.0


Explanation:

    Mean = (20 + 25 + 35 + 40) / 4 = 30

So NaN becomes 30.

In [ ]:
# Example 2: Most Frequent Strategy
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "City": ["Delhi", "Mumbai", np.nan, "Delhi"]
})

imputer = SimpleImputer(strategy="most_frequent")

df["City"] = imputer.fit_transform(df[["City"]]).ravel()

print(df)

     City
0   Delhi
1  Mumbai
2   Delhi
3   Delhi


Since Delhi appears most often, the missing value is replaced with Delhi.

**When to Use**

* Before training almost any ML model.
* Whenever your dataset contains NaN values.



In [ ]:
# Don't use:

imputer.fit_transform(X_test)

In [ ]:
# Do this:

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

The imputer should learn from the training data only.

**10. KNNImputer**

Use

Fills missing values (NaN) using the values of the K nearest (most similar) rows.


Why?

Instead of replacing missing values with a simple mean or median, KNNImputer looks at similar data points and uses their values, which often gives better results.

In [ ]:
# Syntax
KNNImputer(n_neighbors=5)

n_neighbors → Number of nearest rows to consider (default is 5).

In [ ]:
# Example
from sklearn.impute import KNNImputer
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, 25, np.nan, 35, 40],
    "Salary": [30000, 35000, 40000, 45000, 50000]
})

imputer = KNNImputer(n_neighbors=2)

filled_data = imputer.fit_transform(df)

print(filled_data)

[[2.0e+01 3.0e+04]
 [2.5e+01 3.5e+04]
 [3.0e+01 4.0e+04]
 [3.5e+01 4.5e+04]
 [4.0e+01 5.0e+04]]


The missing Age is estimated from the 2 nearest similar rows.

**When to Use**
* Numerical datasets
* When simple mean/median replacement may lose

* important patterns
* Medium-sized datasets

**Don't use it for categorical (text) data.**

      City:

      Delhi

      Mumbai

      NaN

**Use SimpleImputer(strategy="most_frequent") instead.**

Also remember:

In [ ]:
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

**11. ColumnTransformer**

Use

Applies different preprocessing techniques to different columns in a dataset.

Why?

Real-world datasets usually contain:

* Numerical columns → Need scaling.
* Categorical columns → Need encoding.

ColumnTransformer lets you do both in one step.

In [ ]:
# Syntax
ColumnTransformer(
    transformers=[
        ("name", transformer, columns)
    ]
)

In [ ]:
# Example
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 25, 30],
    "Salary": [30000, 40000, 50000],
    "City": ["Delhi", "Mumbai", "Delhi"]
})

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), ["Age", "Salary"]),
        ("cat", OneHotEncoder(), ["City"])
    ]
)

result = preprocessor.fit_transform(df)

print(result)

[[-1.22474487 -1.22474487  1.          0.        ]
 [ 0.          0.          0.          1.        ]
 [ 1.22474487  1.22474487  1.          0.        ]]


**Explanation:**

* Age and Salary → Standardized.
* City → One-hot encoded.

**When to Use**

* Datasets with both numerical and categorical columns.
* Before training almost any real-world ML model.

**Don't preprocess every column the same way.**

For example:

      Age      → Scale ✅

      Salary   → Scale ✅

      City     → OneHotEncode ✅

      Gender   → OneHotEncode ✅

Scaling text columns doesn't make sense.

**12. Pipeline**

Use

Combines multiple preprocessing steps and a machine learning model into a single workflow.

Why?

Instead of manually scaling data, then training a model, then predicting, Pipeline automates everything in the correct order.

In [ ]:
# Syntax
Pipeline([
    ("step_name", transformer),
    ("step_name", model)
])

In [ ]:
# Example
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

# Load dataset
X, y = load_iris(return_X_y=True)

# Create Pipeline
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

# Train
pipeline.fit(X, y)

# Predict
predictions = pipeline.predict(X)

print(predictions[:5])

[0 0 0 0 0]


(Output may vary depending on the dataset.)

What Happens Internally?

Instead of writing:

      scaler = StandardScaler()

      X = scaler.fit_transform(X)

      model = LogisticRegression()

      model.fit(X, y)

      predictions = model.predict(X)

You simply write:

      pipeline.fit(X, y)

      predictions = pipeline.predict(X)

The pipeline automatically:

1. Scales the data.
2. Trains the model.
3. Uses the same scaler during prediction.

**When to Use**
* Almost every real-world ML project.
* When your workflow has multiple preprocessing steps.
* With GridSearchCV and cross-validation.

Don't preprocess outside the pipeline and inside the pipeline.

**Bad:**

      X = scaler.fit_transform(X)

      pipeline = Pipeline([
          ("scaler", StandardScaler()),
          ("model", LogisticRegression())
      ])

This scales the data twice.

**Regression Models**

Regression is used when the output is a continuous numerical value.

**Examples:**

* House Price → ₹50,00,000
* Salary → ₹8,50,000
* Temperature → 32.5°C
* Stock Price → ₹1,250

**1. LinearRegression**

Use

Predicts a continuous numerical value by finding the best-fit straight line through the data.



Why?

It's the simplest and most widely used regression algorithm. It's often the first model to try for regression problems.

In [ ]:
# Syntax
LinearRegression()

In [ ]:
# Example
from sklearn.linear_model import LinearRegression
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = LinearRegression()

# Train model
model.fit(X, y)

# Predict marks for 6 hours
new_data = pd.DataFrame({"Hours": [6]})
prediction = model.predict(new_data)


print(prediction)

[120.]


The algorithm finds the best-fit line that minimizes the prediction errors.

**When to Use**
* House price prediction
* Salary prediction
* Sales forecasting
* Temperature prediction
* Any problem where the relationship is approximately linear

Using Linear Regression for data with a strong curved (non-linear) relationship.

Example:

      Hours → Marks

      1 → 20
      2 → 40
      3 → 70
      4 → 95
      5 → 100

A straight line may not fit this pattern well.

**2. Ridge**

Use

A version of Linear Regression that reduces overfitting by adding a penalty to large coefficients.

Why?

Sometimes Linear Regression fits the training data too closely, leading to poor performance on new data. Ridge helps create a more generalizable model.

Syntax

    Ridge(alpha=1.0)
* alpha → Regularization strength.
    * Larger alpha = More regularization.
    * Smaller alpha = Behaves more like Linear Regressio

In [ ]:
# Example
from sklearn.linear_model import Ridge
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = Ridge(alpha=1.0)

# Train model
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours": [6]}))

print(prediction)

[114.54545455]


**Difference from Linear Regression**

              Linear Regression
                      │
                      ▼
              Fits the data exactly
              (May overfit)

              Ridge Regression
                      │
                      ▼
              Adds a small penalty
              (Reduces overfitting)

**When to Use**
* Dataset has many features.
* Features are highly correlated (multicollinearity).
* Linear Regression is overfitting.

Setting alpha too high.

      Ridge(alpha=1000)

This can make the model underfit, resulting in poor predictions.

**3. Lasso**

Use

A version of Linear Regression that reduces overfitting and can automatically remove unimportant features by making their coefficients exactly 0.


Why?

If your dataset has many features, some may not help the prediction. Lasso can eliminate those unnecessary features, making the model simpler.

**Syntax**

    Lasso(alpha=1.0)
* alpha → Regularization strength.
    * Larger alpha = More features removed.
    * Smaller alpha = Behaves more like Linear Regression.

In [ ]:
# Example
from sklearn.linear_model import Lasso
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = Lasso(alpha=0.1)

# Train model
model.fit(X, y)

# Predict
prediction = model.predict([[6]])

print(prediction)

[119.85]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


**Why is Lasso Special?**

Suppose your dataset has these features:

      Age
      Salary
      Height
      Weight
      Favorite Color
      Pet Name

After training, Lasso might decide:

      Age             ✔
      Salary          ✔
      Height          ✔
      Weight          ✔
      Favorite Color  ❌ (Coefficient = 0)
      Pet Name        ❌ (Coefficient = 0)

It automatically removes irrelevant features.

**When to Use**

High-dimensional datasets (many features)
Feature selection
When some features are likely unimportant

Setting alpha too high.

    Lasso(alpha=100)

This may remove too many features, causing the model to underfit.

In [ ]:
**4. ElasticNet**

Use

Combines Ridge and Lasso into one regression model.

Why?

Sometimes you want:

* Ridge → Reduce overfitting.
* Lasso → Remove unimportant features.

ElasticNet does both.

**Syntax**

      ElasticNet(alpha=1.0, l1_ratio=0.5)
      
**Important Parameters**
* alpha → Regularization strength.
* l1_ratio
    * 0 → Pure Ridge
    * 1 → Pure Lasso
    * 0.5 → Half Ridge + Half Lasso

In [ ]:
# Example
from sklearn.linear_model import ElasticNet
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = ElasticNet(alpha=0.1, l1_ratio=0.5)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours": [6]}))
print(prediction)

[118.46341463]


**When to Use**
* Large datasets
* Many features
* Some features are highly correlated
* You want both regularization and feature selection

Confusing alpha and l1_ratio.

* alpha → Controls how much regularization.
* l1_ratio → Controls which type of regularization (Lasso vs Ridge).

**5. DecisionTreeRegressor**

Use

Predicts continuous numerical values by splitting the data into smaller groups using decision rules (like a flowchart).

Why?

Unlike Linear Regression, it doesn't assume a straight-line relationship. It can learn complex and non-linear patterns.

**Syntax**

      DecisionTreeRegressor()

In [ ]:
# Example
from sklearn.tree import DecisionTreeRegressor
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = DecisionTreeRegressor(random_state=42)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[3.5]}))

print(prediction)

[60.]


**How It Works**

Instead of fitting one straight line, it keeps asking questions like:

              Hours <= 3?

                    Yes
                    │
                    ▼
                Hours <= 2?
                    │
                Yes     No
              20,40    60

                    No
                    │
                    ▼
              Hours <= 4?
              80       100

It follows the path and predicts the value at the final node (leaf).

**Important Parameters**
* max_depth → Maximum depth of the tree.
* random_state → Makes results reproducible.
* min_samples_split → Minimum samples needed to split a node.

**When to Use**
* Non-linear relationships
* Complex datasets
* When Linear Regression performs poorly

**Common Mistake**

Leaving the tree unrestricted.

    DecisionTreeRegressor()

This can overfit the training data.

**A better approach is often:**

    DecisionTreeRegressor(max_depth=5, random_state=42)

**6. RandomForestRegressor**

Use

Predicts continuous numerical values using multiple Decision Trees instead of just one.

Why?

A single Decision Tree can easily overfit. Random Forest combines many trees and averages their predictions, making the model more accurate and stable.

**Syntax**

      RandomForestRegressor()

In [ ]:
# Example
from sklearn.ensemble import RandomForestRegressor
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[3.5]}))

print(prediction)

[62.4]


(Exact output may vary.)

**How It Works**

Instead of one tree:

      Decision Tree
            │
            ▼
      Prediction = 60

Random Forest builds many trees:

      Tree 1 → 65
      Tree 2 → 70
      Tree 3 → 68
      Tree 4 → 66
      Tree 5 → 71

      Final Prediction = Average = 68

This makes predictions much more reliable.

**Important Parameters**
* n_estimators → Number of trees (default = 100)
* max_depth → Maximum depth of each tree
* random_state → Makes results reproducible

**When to Use**
* Medium to large datasets
* Complex or non-linear relationships
* When you need better accuracy than a single Decision Tree

**Common Mistake**

Using very few trees.

    RandomForestRegressor(n_estimators=5)

A small number of trees may not perform well.

**A common choice is:**

    RandomForestRegressor(n_estimators=100)

**7. GradientBoostingRegressor**

Use

Predicts continuous numerical values by building multiple Decision Trees one after another, where each new tree corrects the mistakes of the previous tree.

Why?

Instead of creating many independent trees like Random Forest, Gradient Boosting learns step by step, making it one of the most accurate regression algorithms.

Syntax

    GradientBoostingRegressor()

In [ ]:
# Example
from sklearn.ensemble import GradientBoostingRegressor
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[3.5]}))

print(prediction)

[60.]


**How It Works**

      Initial Prediction = 60

                ↓

      Tree 1
      Predicts correction: +8

      New Prediction = 68

                ↓

      Tree 2
      Predicts correction: +1.5

      New Prediction = 69.5

                ↓

      Tree 3
      Predicts correction: +0.3

      Final Prediction = 69.8

  Each new tree focuses on reducing the errors made by the previous trees.

**Important Parameters**

* n_estimators → Number of trees.
* learning_rate → How much each tree contributes.
* max_depth → Maximum depth of each tree.
* random_state → Makes results reproducible.

**When to Use**
* Complex datasets
* High prediction accuracy is important
* Kaggle competitions
* House price prediction
* Sales forecasting

**Common Mistake**

Setting a very high learning_rate.

    GradientBoostingRegressor(learning_rate=1)

This can cause poor performance.

**A common choice is:**

    GradientBoostingRegressor(learning_rate=0.1)

**8. SVR (Support Vector Regressor)**

Use

Predicts continuous numerical values using the Support Vector Machine (SVM) algorithm.


Why?

Unlike Linear Regression, SVR can learn complex and non-linear relationships, making it useful when the data doesn't follow a straight line.

**Syntax**

    SVR(kernel="rbf")

**Important Parameters**
* kernel → Type of function used to fit the data ("linear", "rbf", "poly")
* C → Controls how strictly the model fits the training data.
* epsilon → Defines an acceptable error margin.

In [ ]:
# Example
from sklearn.svm import SVR
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = SVR(kernel="rbf")

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[3.5]}))

print(prediction)

[60.83855997]


(Exact value may vary.)

**When to Use**
* Non-linear datasets
* Small to medium-sized datasets
* Complex prediction problems

**Common Mistake**

Not scaling the data.

SVR is very sensitive to feature scales.

**Always do:**

      from sklearn.preprocessing import StandardScaler

      scaler = StandardScaler()

      X = scaler.fit_transform(X)

before training the SVR model.

**9. KNeighborsRegressor**

Use

Predicts a continuous numerical value by looking at the K nearest (most similar) data points.


Why?

Instead of learning a formula, it predicts based on the values of nearby data points.

**Syntax**

    KNeighborsRegressor(n_neighbors=5)

**Important Parameters**
* n_neighbors → Number of nearest neighbors to consider.

In [ ]:
# Example
from sklearn.neighbors import KNeighborsRegressor
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
})

X = df[["Hours"]]
y = df["Marks"]

# Create model
model = KNeighborsRegressor(n_neighbors=2)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[3.5]}))

print(prediction)

[70.]


**How It Works**

Suppose you want to predict marks for 3.5 hours.

Nearby students are:

    Hours   Marks
    3        60
    4        80

Average:

    (60 + 80) / 2 = 70

So the prediction is:

    70

**When to Use**
* Small datasets
* Non-linear data
* When similar inputs should produce similar outputs

**Common Mistake**

Forgetting to scale the data.

Since KNN uses distance, features with larger values dominate.

**Always scale first:**

    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()

    X = scaler.fit_transform(X)

**Classification Models**

Classification is used when the output is a category (label) instead of a number.

Examples:

* Spam / Not Spam
* Positive / Negative Review
* Disease / No Disease
* Buy / Not Buy
* Cat / Dog

If the output is a label, it's a Classification problem.

**1. LogisticRegression**

Use

Predicts categories (labels) such as Yes/No, Spam/Not Spam, or Pass/Fail.

Why?

Despite its name, Logistic Regression is a classification algorithm, not a regression algorithm.

**Syntax**

    LogisticRegression()

In [ ]:
# Example
from sklearn.linear_model import LogisticRegression
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Pass": [0, 0, 1, 1, 1]
})

X = df[["Hours"]]
y = df["Pass"]

# Create model
model = LogisticRegression()

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[2.5]}))

print(prediction)

# Predict Probability
print(model.predict_proba(pd.DataFrame({"Hours":[2.5]})))

[1]
[[0.47920043 0.52079957]]


Meaning:

    1 = Pass
    0 = Fail

So the model predicts:

    Pass

Predict Probability

    print(model.predict_proba([[2.5]]))

Output (Approx.)

    [[0.30 0.70]]

Meaning:

    30% chance of Fail
    70% chance of Pass

**Important Parameters**
* random_state → Makes results reproducible.
* max_iter → Maximum training iterations.

Example:

    LogisticRegression(random_state=42, max_iter=1000)

**Common Mistake**

Thinking it's a regression algorithm because of its name.

It is **always used for classification.**

Also, scale your features for better performance:

    from sklearn.preprocessing import StandardScaler

**2. DecisionTreeClassifier**

Use

Predicts categories (labels) by making a series of Yes/No decisions, just like a flowchart.

Why?

Unlike Logistic Regression, it can learn complex and non-linear patterns without requiring the data to be linear.

Syntax

    DecisionTreeClassifier()

In [ ]:
# Example
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Pass": [0, 0, 1, 1, 1]
})

X = df[["Hours"]]
y = df["Pass"]

# Create model
model = DecisionTreeClassifier(random_state=42)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[2.5]}))

print(prediction)

[0]


Meaning:

    1 = Pass
    0 = Fail

**How It Works**

The tree keeps asking questions until it reaches a decision.

    Hours <= 2?

          Yes
          │
      Predict: Fail (0)

          No
          │
      Predict: Pass (1)

Every prediction follows a path through the tree.

**Important Parameters**
* max_depth → Maximum depth of the tree.
* random_state → Makes results reproducible.
* criterion → How the tree chooses the best split ("gini" is default, "entropy" is another option).

**When to Use**
* Spam detection
* Disease prediction
* Customer churn prediction
* Credit approval
* Any non-linear classification problem

**Common Mistake**

Letting the tree grow without limits.

    DecisionTreeClassifier()

This can **overfit** the training data.

Better:

    DecisionTreeClassifier(max_depth=5, random_state=42)

**3. RandomForestClassifier**
Use

Predicts categories (labels) using multiple Decision Trees instead of just one.

Why?

A single Decision Tree can make mistakes or overfit. RandomForestClassifier combines the predictions of many trees and chooses the majority vote, making it more accurate and reliable.

Syntax

    RandomForestClassifier()

In [ ]:
# Example
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Pass": [0, 0, 1, 1, 1]
})

X = df[["Hours"]]
y = df["Pass"]

# Create model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[2.5]}))

print(prediction)

[0]


Meaning:

    1 = Pass
    0 = Fail

**How It Works**

Instead of one tree:

    Decision Tree
          │
          ▼
    Predict = Pass

Random Forest creates many trees:

    Tree 1 → Pass ✅
    Tree 2 → Pass ✅
    Tree 3 → Fail ❌
    Tree 4 → Pass ✅
    Tree 5 → Pass ✅

    Final Prediction = Pass
    (Majority Vote)

**Important Parameters**
* n_estimators → Number of trees (default = 100)
* max_depth → Maximum depth of each tree
* random_state → Makes results reproducible

**When to Use**
* Spam detection
* Fraud detection
* Disease prediction
* Customer churn prediction
* Credit risk analysis
* Most real-world classification problems

**Common Mistake**

Using very few trees.

    RandomForestClassifier(n_estimators=5)

**Better:**

    RandomForestClassifier(n_estimators=100)

More trees generally improve stability (though training takes longer).

**4. KNeighborsClassifier**

Use

Predicts categories (labels) by looking at the K nearest (most similar) data points.


Why?

Instead of learning a mathematical model, it classifies a new data point based on the majority class of its nearest neighbors.

Syntax

    KNeighborsClassifier(n_neighbors=5)

**Important Parameters**
* n_neighbors → Number of nearest neighbors to consider.

In [ ]:
# Example
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Pass": [0, 0, 1, 1, 1]
})

X = df[["Hours"]]
y = df["Pass"]

# Create model
model = KNeighborsClassifier(n_neighbors=3)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[2.5]}))

print(prediction)

[0]


**Meaning:**

    1 = Pass
    0 = Fail

**How It Works**

Suppose you want to predict for 2.5 hours.

**Nearest neighbors:**

    Hours   Pass
    2        0
    3        1
    4        1

Votes:

    Pass → 2 votes
    Fail → 1 vote

Final Prediction:

    Pass (1)

**Important Parameters**
* n_neighbors → Number of neighbors.
weights
* "uniform" → All neighbors have equal importance.
* "distance" → Closer neighbors have more influence.

**When to Use**
* Small datasets
* Pattern recognition
* Recommendation systems
* Simple classification problems

**Common Mistake**

Forgetting to scale the data.

KNN uses distance, so features with larger values dominate.

**Always scale first:**

    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()

    X = scaler.fit_transform(X)

**5. SVC (Support Vector Classifier)**

Use

Predicts categories (labels) by finding the best boundary (decision boundary) that separates different classes.

Why?

SVC tries to create the largest possible gap (margin) between classes, which often leads to better predictions on new data.

Syntax

    SVC(kernel="rbf")

**Important Parameters**
* kernel → Type of decision boundary ("linear", "rbf", "poly", "sigmoid")
* C → Controls how strictly the model classifies the data.
* gamma → Controls how much influence each data point has (used with "rbf" and "poly" kernels).

In [ ]:
# Example
from sklearn.svm import SVC
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Pass": [0, 0, 1, 1, 1]
})

X = df[["Hours"]]
y = df["Pass"]

# Create model
model = SVC(kernel="linear")

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[2.5]}))

print(prediction)

[1]


**Meaning:**

    1 = Pass
    0 = Fail
    
**How It Works**

Instead of simply separating classes, SVC finds the widest possible margin.

    Fail      Margin      Pass

    ● ● ●   |--------|   ▲ ▲ ▲

The boundary in the middle is chosen because it maximizes the distance between the two classes.

**When to Use**
* Text classification
* Image classification
* Face recognition
* Medium-sized datasets
* Complex classification problems

**Common Mistake**

Not scaling the data.

SVC is **very sensitive** to feature scales.

**Always scale first:**

    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()

    X = scaler.fit_transform(X)

In [ ]:
# Example

from sklearn.naive_bayes import GaussianNB
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Pass": [0, 0, 1, 1, 1]
})

X = df[["Hours"]]
y = df["Pass"]

# Create model
model = GaussianNB()

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[2.5]}))

print(prediction)

#Predict Probability
print(model.predict_proba([[2.5]]))

[1]


Meaning:

    1 = Pass
    0 = Fail

**Predict Probability**

    print(model.predict_proba([[2.5]]))

Output (Approx.)

    [[0.25 0.75]]

Meaning:

* 25% chance of Fail
* 75% chance of Pass

**Important Parameters**

GaussianNB doesn't have many important parameters.

**The most common one is:**

    GaussianNB(var_smoothing=1e-9)

* var_smoothing → Prevents numerical errors during training. The default value works well in most cases.

**When to Use**
* Spam detection
* Email classification
* Text classification
* Sentiment analysis
* Small datasets
* Very fast predictions

**Common Mistake**

Don't -> Assuming Naive Bayes always gives the highest accuracy.

It is **very fast**, but algorithms like Random Forest or Gradient Boosting often achieve higher accuracy on many datasets.

**7. GradientBoostingClassifier**

Use

Predicts categories (labels) by building multiple Decision Trees sequentially, where each new tree corrects the mistakes of the previous trees.

Why?

Instead of building many independent trees like Random Forest, Gradient Boosting improves the model step by step, often achieving higher accuracy.

Syntax

    GradientBoostingClassifier()

In [ ]:
# Example
from sklearn.ensemble import GradientBoostingClassifier
import pandas as pd

# Dataset
df = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5],
    "Pass": [0, 0, 1, 1, 1]
})

X = df[["Hours"]]
y = df["Pass"]

# Create model
model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

# Train
model.fit(X, y)

# Predict
prediction = model.predict(pd.DataFrame({"Hours":[2.5]}))

print(prediction)

# Predict Probability
print(model.predict_proba(pd.DataFrame({"Hours":[2.5]})))

[0]
[[9.99974028e-01 2.59717334e-05]]


How It Works

        Tree 1
        Predicts ❌

              ↓ Learns from mistake

        Tree 2
        Improves prediction ❌

              ↓ Learns again

        Tree 3
        Improves more ✔

              ↓

        Final Prediction

Each tree focuses on correcting the errors made by the previous trees.

**Important Parameters**
* n_estimators → Number of trees.
* learning_rate → How much each tree contributes.
* ax_depth → Maximum depth of each tree.
* random_state → Makes results reproducible.

**When to Use**
* Fraud detection
* Customer churn prediction
* Medical diagnosis
* Credit risk prediction
* Kaggle competitions
* Complex classification datasets

**Common Mistake**

Don't -> Setting a very high learning rate.

    GradientBoostingClassifier(learning_rate=1)

This may cause the model to perform poorly.

**A better choice is:**

    GradientBoostingClassifier(learning_rate=0.1)