<a href="https://colab.research.google.com/github/JennaSanks/ML_Libraries/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow

##Tensor Basics

###import tensorflow as tf

**What is it?**

Imports the TensorFlow library into your Python program.

**Why is it used?**

Without importing TensorFlow, you can't use any of its features.

**Syntax**

    import tensorflow as tf

In [1]:
import tensorflow as tf

print(tf.__version__)

2.20.0


(The version number depends on your installed TensorFlow version.)

###tf.constant()

**Definition**

Creates a constant tensor.

A tensor is TensorFlow's basic data structure, similar to a NumPy array.

  Tensor: A multidimensional array used to store and process data in TensorFlow.

**Why is it used?**

Almost everything in TensorFlow (inputs, weights, outputs) is represented as tensors.

**Syntax**

    tf.constant(value)

In [2]:
# Example 1: 1D Tensor
import tensorflow as tf

a = tf.constant([10, 20, 30])

print(a)

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


**Explanation**

* Values → [10, 20, 30]
* Shape → (3,) (3 elements)
* Data type → int32

In [3]:
# Example 2: 2D Tensor
import tensorflow as tf

matrix = tf.constant([
    [1, 2],
    [3, 4]
])

print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
# Example 3: Float Tensor
import tensorflow as tf

a = tf.constant([1.5, 2.7, 3.8])

print(a)

tf.Tensor([1.5 2.7 3.8], shape=(3,), dtype=float32)


In [5]:
# Example 4: String Tensor
import tensorflow as tf

names = tf.constant(["Alice", "Bob"])

print(names)

tf.Tensor([b'Alice' b'Bob'], shape=(2,), dtype=string)


In [6]:
# Example 5: Boolean Tensor
import tensorflow as tf

flags = tf.constant([True, False, True])

print(flags)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


**Why use tf.constant()?**

Use it when the values should not change.

Examples:

* Input data
* Labels
* Fixed matrices
* Configuration values

###tf.Variable()

**Definition

Creates a mutable tensor.

    Mutable: Can be changed after it is created.

**Why is it used?**

Machine learning models learn by updating their parameters (weights and biases). Those values must be mutable.

**Syntax**

    tf.Variable(value)

In [7]:
# Example 1
import tensorflow as tf

x = tf.Variable(10)

print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [8]:
# Example 2: Updating a Variable
import tensorflow as tf

x = tf.Variable(10)

x.assign(25)

print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>


In [9]:
# Example 3: Adding to a Variable
import tensorflow as tf

x = tf.Variable(5)

x.assign_add(10)

print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=15>


In [10]:
# Example 4: Subtracting
import tensorflow as tf

x = tf.Variable(20)

x.assign_sub(7)

print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=13>


**Why use tf.Variable()?**

During training:

    Old Weight → Calculate Gradient → Update Weight

Only tf.Variable allows those updates.

tf.constant() vs tf.Variable()
| Feature           | `tf.constant()` | `tf.Variable()`      |
| ----------------- | --------------- | -------------------- |
| Mutable           | ❌ No            | ✅ Yes                |
| Used for          | Fixed values    | Trainable parameters |
| Can change later? | ❌               | ✅                    |
| Common use        | Input data      | Model weights        |


###tf.convert_to_tensor()

**Definition**

Converts Python objects or NumPy arrays into TensorFlow tens

**Why is it used?**

Many datasets begin as Python lists or NumPy arrays. TensorFlow operations require tensors, so this function converts them.

In [11]:
# Example 1: List → Tensor
import tensorflow as tf

numbers = [1, 2, 3, 4]

tensor = tf.convert_to_tensor(numbers)

print(tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [12]:
# Example 2: NumPy Array → Tensor
import tensorflow as tf
import numpy as np

arr = np.array([10, 20, 30])

tensor = tf.convert_to_tensor(arr)

print(tensor)

tf.Tensor([10 20 30], shape=(3,), dtype=int64)


In [13]:
# Example 3: Specify Data Type
import tensorflow as tf

numbers = [1, 2, 3]

tensor = tf.convert_to_tensor(numbers, dtype=tf.float32)

print(tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


**When should you use each?**

**tf.constant()**

When you're creating a new tensor from scratch.

    a = tf.constant([1, 2, 3]

**tf.Variable()**

When the value needs to change during training.

    weight = tf.Variable(0.5)

**tf.convert_to_tensor()**

When you already have data in another format.

    import numpy as np

    arr = np.array([1, 2, 3])

    tensor = tf.convert_to_tensor(arr)

##Tensor Properties

In NumPy, you learned:

* shape
* ndim
* size
* dtype

TensorFlow has almost the same properties, but with a few TensorFlow-specific methods.

###tensor.shape

**Definition**

Returns the shape (dimensions) of a tensor.

**Why is it used?**

Before feeding data into a neural network, you must know its shape. Many TensorFlow errors happen because of incorrect shapes.

**Syntax**

    tensor.shape

In [14]:
# Example 1
import tensorflow as tf

tensor = tf.constant([
    [1,2,3],
    [4,5,6]
])

print(tensor.shape)

(2, 3)


Meaning:

* 2 rows
* 3 columns

In [15]:
# Example 2
import tensorflow as tf

tensor = tf.constant([1,2,3,4])

print(tensor.shape)

(4,)


*Meaning:*

4 elements in one dimension.

In [16]:
# Example 3 (3D Tensor)
import tensorflow as tf

tensor = tf.constant([
    [[1],[2]],
    [[3],[4]]
])

print(tensor.shape)

(2, 2, 1)


**Meaning**

    2 blocks

    Each block has

    2 rows

    Each row has

    1 value

###tensor.ndim

**Definition**

Returns the number of dimensions (rank) of the tensor.

    Rank: The number of axes (dimensions) a tensor has.

**Why is it used?**

Deep learning models expect tensors of specific ranks:

* Images → rank 4
* Text sequences → rank 2 or 3
* Single feature vectors → rank 2

**Syntax**

    tensor.ndim

In [17]:
# Example 1
import tensorflow as tf

tensor = tf.constant([1,2,3])

print(tensor.ndim)

1


In [18]:
# Example 2
import tensorflow as tf

tensor = tf.constant([
    [1,2],
    [3,4]
])

print(tensor.ndim)

2


In [19]:
# Example 3
import tensorflow as tf

tensor = tf.constant([
    [[1],[2]],
    [[3],[4]]
])

print(tensor.ndim)

3


**Understanding Dimensions**

Scalar
    tf.constant(5)

Rank

    0

**Vector**

    tf.constant([1,2,3])

Rank

    1

**Matrix**

    tf.constant([
        [1,2],
        [3,4]
    ])

Rank

    2

**3D Tensor**

    tf.constant([
        [[1],[2]],
        [[3],[4]]
    ])

Rank

    3

###tensor.dtype

**Definition**

Returns the tensor's data type.

**Why is it used?**

Neural networks often require floating-point numbers (float32). Checking the data type helps avoid type mismatch errors.

**Syntax**

    tensor.dtype

In [20]:
# Example 1
import tensorflow as tf

tensor = tf.constant([1,2,3])

print(tensor.dtype)

<dtype: 'int32'>


In [21]:
# Example 2
import tensorflow as tf

tensor = tf.constant([1.5,2.8])

print(tensor.dtype)

<dtype: 'float32'>


In [22]:
# Example 3
import tensorflow as tf

tensor = tf.constant([True,False])

print(tensor.dtype)

<dtype: 'bool'>


**Common TensorFlow Data Types**

      tf.int32

      tf.int64

      tf.float16

      tf.float32

      tf.float64

      tf.bool

      tf.string

###tf.size()

**Definition**

Returns the total number of elements in a tensor.

**Why is it used?**

Useful for:

* Checking dataset size
* Validating reshaping operations
* Counting elements

**Syntax**

    tf.size(tensor)

In [23]:
# Example 1
import tensorflow as tf

tensor = tf.constant([
    [1,2,3],
    [4,5,6]
])

print(tf.size(tensor))

tf.Tensor(6, shape=(), dtype=int32)


There are 6 values.

In [26]:
# Example 2
import tensorflow as tf

tensor = tf.constant([1,2,3])

print(tf.size(tensor))

tf.Tensor(3, shape=(), dtype=int32)


###tf.rank()

**Definition**

Returns the number of dimensions (rank) of a tensor.

**Why use it if ndim exists?**

* tensor.ndim gives a Python integer-like property.
* tf.rank() returns a TensorFlow tensor, which is useful inside TensorFlow graphs and functions.

**Syntax**

    tf.rank(tensor)

In [24]:
# Example
import tensorflow as tf

tensor = tf.constant([
    [1,2],
    [3,4]
])

print(tf.rank(tensor))

tf.Tensor(2, shape=(), dtype=int32)


###tf.shape()

**Definition**

Returns the tensor's shape as a TensorFlow tensor.

**Why use it?**

Like tf.rank(), it works well inside TensorFlow functions and computational graphs.

**Syntax**
    tf.shape(tensor)

In [31]:
# Example
import tensorflow as tf

tensor = tf.constant([
    [1,2,3],
    [4,5,6]
])

print(tf.shape(tensor))

tf.Tensor([2 3], shape=(2,), dtype=int32)


##tensor.shape vs tf.shape()

###tensor.shape

In [30]:
print(tensor.shape)

(2, 3)


Returns a Python shape object.

###tf.shape()

In [28]:
print(tf.shape(tensor))

tf.Tensor([3], shape=(1,), dtype=int32)


Returns a TensorFlow tensor.

##Tensor Operations

Now that you know what tensors are and how to inspect them, it's time to perform operations on them.

This is equivalent to learning mathematical operations in NumPy.

###tf.add()

**Definition**

Adds two tensors element-wise.

**Element-wise:** The operation is performed on corresponding elements in the tensors.

**Why is it used?**

Addition is used everywhere in deep learning:

* Adding bias to neurons
* Updating values
* Tensor calculations

**Syntax**

    tf.add(x, y)

In [32]:
# Example 1
import tensorflow as tf

a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

result = tf.add(a, b)

print(result)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


**Explanation**

    1+4=5

    2+5=7

    3+6=9

In [33]:
# Example 2
import tensorflow as tf

a = tf.constant(10)
b = tf.constant(20)

print(tf.add(a,b))

tf.Tensor(30, shape=(), dtype=int32)


###tf.subtract()

**Definition**

Subtracts one tensor from another.

**Syntax**

    tf.subtract(x,y)

In [34]:
# Example
import tensorflow as tf

a = tf.constant([10,20,30])
b = tf.constant([1,2,3])

print(tf.subtract(a,b))

tf.Tensor([ 9 18 27], shape=(3,), dtype=int32)


###tf.multiply()

**Definition**

Multiplies tensors element-wise.

**Syntax**

    tf.multiply(x,y)

In [35]:
# Example
import tensorflow as tf

a = tf.constant([2,4,6])
b = tf.constant([3,5,7])

print(tf.multiply(a,b))

tf.Tensor([ 6 20 42], shape=(3,), dtype=int32)


**Explanation**

    2×3=6

    4×5=20

    6×7=42

###tf.divide()

**Definition**

Performs element-wise division.

**Syntax**

    tf.divide(x,y)

In [36]:
# Example
import tensorflow as tf

a = tf.constant([20,30,40])
b = tf.constant([2,3,5])

print(tf.divide(a,b))

tf.Tensor([10. 10.  8.], shape=(3,), dtype=float64)


Notice the result is floating-point.

###tf.matmul()

**Definition**

Performs matrix multiplication.

**Matrix multiplication:**

Combines rows of the first matrix with columns of the second matrix according to linear algebra rules.

**Why is it used?**

This is one of the most important TensorFlow operations.

Every neural network computes something like:

    Output = Input × Weights + Bias

The *Input × Weights* part is matrix multiplication.

**Syntax**

    tf.matmul(a,b)

In [37]:
# Example
import tensorflow as tf

a = tf.constant([
    [1,2],
    [3,4]
])

b = tf.constant([
    [5,6],
    [7,8]
])

print(tf.matmul(a,b))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


###Matrix Multiplication vs Element-wise Multiplication

In [38]:
# Element-wise

print(tf.multiply(a,b))

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [39]:
# Matrix multiplication

print(tf.matmul(a,b))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


They are completely different operations.

###tf.square()

Squares every element.

**Syntax**

    tf.square(x)

In [40]:
# Example
import tensorflow as tf

a = tf.constant([2,3,4])

print(tf.square(a))

tf.Tensor([ 4  9 16], shape=(3,), dtype=int32)


###tf.sqrt()

Square root.

**Syntax**

    tf.sqrt(x)

In [41]:
# Example
import tensorflow as tf

a = tf.constant([4.0,9.0,16.0])

print(tf.sqrt(a))

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


###tf.pow()

Raise values to a power.

**Syntax**

    tf.pow(x, power)

In [42]:
# Example
import tensorflow as tf

a = tf.constant([2,3,4])

print(tf.pow(a,3))

tf.Tensor([ 8 27 64], shape=(3,), dtype=int32)


###tf.abs()

Absolute value.

**Syntax**

    tf.abs(x)

In [43]:
# Example
import tensorflow as tf

a = tf.constant([-5,4,-3])

print(tf.abs(a))

tf.Tensor([5 4 3], shape=(3,), dtype=int32)


###tf.maximum()

Returns the larger value from two tensors element-wise.

**Syntax**

    tf.maximum(a,b)

In [44]:
# Example
import tensorflow as tf

a = tf.constant([1,8,3])
b = tf.constant([5,2,9])

print(tf.maximum(a,b))

tf.Tensor([5 8 9], shape=(3,), dtype=int32)


###tf.minimum()

Returns the smaller value element-wise.

In [45]:
import tensorflow as tf

a = tf.constant([1,8,3])
b = tf.constant([5,2,9])

print(tf.minimum(a,b))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


###Operator Shortcuts

TensorFlow also supports Python operators.

**Instead of**

    tf.add(a,b)

**you can write**

    a+b

**Instead of**

    tf.subtract(a,b)

**you can write**

    a-b

**Instead of**

    tf.multiply(a,b)

**you can write**

    a*b


Instead of

    tf.divide(a,b)

**you can write**

    a/b

In [46]:
# Example

import tensorflow as tf

a = tf.constant([2,4,6])
b = tf.constant([1,2,3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

tf.Tensor([3 6 9], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([ 2  8 18], shape=(3,), dtype=int32)
tf.Tensor([2. 2. 2.], shape=(3,), dtype=float64)


##Reshaping & Manipulating Tensors

###tf.reshape()

**Definition**

Changes the shape of a tensor without changing its data.

**Reshape**:

Rearranges the dimensions while keeping the same values.

**Why is it used?**

Neural networks require inputs of specific shapes.

**Example:**

Original:

    [1,2,3,4,5,6]

    ↓

Reshape

    ↓

    [[1,2,3],
    [4,5,6]]

**Syntax**

    tf.reshape(tensor, new_shape)

In [47]:
# Example 1
import tensorflow as tf

tensor = tf.constant([1,2,3,4,5,6])

new_tensor = tf.reshape(tensor, (2,3))

print(new_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [48]:
# Example 2
tensor = tf.constant([1,2,3,4,5,6])

print(tf.reshape(tensor,(3,2)))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Example 3 (Automatic Size)

Use -1.

In [49]:
tensor = tf.constant([1,2,3,4,5,6])

print(tf.reshape(tensor,(-1,2)))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


TensorFlow automatically calculates the missing dimension.

**Why -1 is Useful**

Instead of manually counting:

    tf.reshape(x,(128,784))

Use

    tf.reshape(x,(-1,784))

TensorFlow determines the correct number of rows automatically.

Very common in Deep Learning.

##tf.transpose()

**Definition**

Swaps rows and columns

**Why is it used?**

Many ML algorithms expect data in different orientations.

**Syntax**

    tf.transpose(tensor)

In [50]:
# Example
import tensorflow as tf

matrix = tf.constant([
    [1,2,3],
    [4,5,6]
])

print(tf.transpose(matrix))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


**Notice**

Rows became columns.

**Example 2**

Before

    1 2 3

    4 5 6

After

    1 4

    2 5

    3 6

###tf.concat()

**Definition**

Joins tensors together.

**Why is it used?**

Common when:

* Combining datasets
* Joining features
* Merging embeddings

**Syntax**

    tf.concat([tensor1,tensor2], axis)

In [51]:
# Example 1
import tensorflow as tf

a = tf.constant([1,2,3])

b = tf.constant([4,5,6])

print(tf.concat([a,b], axis=0))

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [52]:
# Example 2 (Rows)
a = tf.constant([
    [1,2],
    [3,4]
])

b = tf.constant([
    [5,6]
])

print(tf.concat([a,b], axis=0))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [53]:
# Example 3 (Columns)
a = tf.constant([
    [1],
    [2]
])

b = tf.constant([
    [10],
    [20]
])

print(tf.concat([a,b], axis=1))

tf.Tensor(
[[ 1 10]
 [ 2 20]], shape=(2, 2), dtype=int32)


**Understanding axis**
    axis=0

    ↓

    Vertical

    ↓

    Add rows

]

    axis=1

    ↓

    Horizontal

    ↓

    Add columns

###tf.stack()

**Definition**

Stacks tensors into a new dimension.

**Difference from concat()**

**concat()** joins existing dimensions.

**stack()** creates a brand-new dimension.

In [54]:
# Example
import tensorflow as tf

a = tf.constant([1,2,3])

b = tf.constant([4,5,6])

print(tf.stack([a,b]))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Shape

    (2,3)

In [55]:
# Stack Along Columns
print(tf.stack([a,b], axis=1))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


Concat vs Stack

Concat

    [1 2 3]

    +

    [4 5 6]

    ↓

    [1 2 3 4 5 6]

Stack

    [1 2 3]

    [4 5 6]

    ↓

    [[1 2 3]
    [4 5 6]]

##tf.squeeze()

**Definition**

Removes dimensions of size 1.

**Why?**

Models often produce unnecessary dimensions.

In [56]:
# Example
import tensorflow as tf

tensor = tf.constant([[[5]]])

print(tensor.shape)

print(tf.squeeze(tensor))

print(tf.squeeze(tensor).shape)

(1, 1, 1)
tf.Tensor(5, shape=(), dtype=int32)
()


In [57]:
# Another Example
tensor = tf.constant([[1],[2],[3]])

print(tf.squeeze(tensor))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


##tf.expand_dims()

**Definition**

Adds a new dimension.

**Why?**

Neural networks expect extra dimensions.

For example

Image

    Height

    Width

    ↓

    Need

    Batch

    Height

    Width

    Channels

Syntax
    tf.expand_dims(tensor, axis)

In [58]:
# Example
import tensorflow as tf

tensor = tf.constant([1,2,3])

print(tf.expand_dims(tensor, axis=0))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


Shape

    (1,3)

In [59]:
# Example 2
print(tf.expand_dims(tensor, axis=1))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


Shape

    (3,1)

##Broadcasting

**Definition**

TensorFlow automatically expands smaller tensors during operations.

In [60]:
# Example

import tensorflow as tf

a = tf.constant([1,2,3])

print(a + 10)

tf.Tensor([11 12 13], shape=(3,), dtype=int32)


TensorFlow behaves as if

    10

    ↓

    [10 10 10]

In [61]:
# Another Example

matrix = tf.constant([
    [1,2],
    [3,4]
])

print(matrix + 5)

tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)


**Why Broadcasting Matters**

Instead of writing

    [10,10,10]

You simply write

    10

TensorFlow does the rest.

###Tensor ↔ NumPy Conversion

TensorFlow and NumPy work together seamlessly.

In [62]:
# Tensor → NumPy
import tensorflow as tf

tensor = tf.constant([1,2,3])

print(tensor.numpy())

[1 2 3]


Type

    NumPy ndarray

In [63]:
# NumPy → Tensor
import tensorflow as tf
import numpy as np

arr = np.array([10,20,30])

tensor = tf.convert_to_tensor(arr)

print(tensor)

tf.Tensor([10 20 30], shape=(3,), dtype=int64)
